### ISSUE TITLE
select2问题，初次加载选择完成后选择框没有消失

### ISSUE THREAD

**Issue by ononl** [Sparkinzy/dcat-distpicker#4]
![image](https://user-images.githubusercontent.com/48144651/194737154-4110d039-dd9a-454f-bca9-b3a6eb9fca2d.png)

**Comment by Sparkinzy** [comment]
> ![image](https://user-images.githubusercontent.com/48144651/194737154-4110d039-dd9a-454f-bca9-b3a6eb9fca2d.png)


我试试~

**Comment by Sparkinzy** [comment]
最新版 1.1.0 已经修复这个问题
